### ISSUE TITLE
cmo_maf2maf spits out core dumps

### ISSUE THREAD

**Issue by kpjonsson** [mskcc/cmo#12]
Just ran `cmo_maf2maf --input-maf big.maf --output-maf big.vep.maf --custom-enst /opt/common/CentOS_6-dev/vcf2maf/develop/data/isoform_overrides_at_mskcc --vep-forks 20`. I got an output file that looks allright, but my directory was also filled up with 2222 files along the lines of `core.30920`.

**Comment by kpjonsson** [comment]
Tabix issue, solved.

**Comment by ckandoth** [comment]
Currently solved with updating tabix. But will implement a more graceful fix in the main Perl code - https://github.com/mskcc/vcf2maf/issues/111
