### ISSUE TITLE
cmo_gdc tool bug in creating log folder

### ISSUE THREAD

**Issue by ckandoth** [mskcc/cmo#18]
Here's a sample command for Luna that tries to download a small 100MB miRNA-Seq BAM:
```bash
cmo_gdc --experimental_strategy miRNA-Seq --data_type AlignedReads --output_file test.tsv --token_file /ifs/tcga/gdc/token/gdc-user-token.taylorb.txt --participant_id TCGA-44-2656
```
The `gdc-client` script works fine on its own for downloading this file. The issue is this exception:
```bash
Exception caught: <type 'exceptions.IOError'>, line number: 820
Check logs in: /ifs/tcga/gdc/jobs/job.14301562.20170503-144945/a233689d-00c6-4eeb-ad82-5122317f42e6
Continuing ...
```
For some reason, the `mkdir_p` function in cmo_gdc is unable to create the subfolder named `a233689d-00c6-4eeb-ad82-5122317f42e6` (based on the GDC file ID), and errors out when it tries to open it for reading (to parse for a line that says the job was "successful").

**Comment by ckandoth** [comment]
@cband I think you handled this issue, correct? By getting `/ifs/tcga` mounted across all nodes with r/w rights?

**Comment by cband** [comment]
Yes, this should be resolved.
