### ISSUE TITLE
cmo_bwa_mem returns incorrect exit code

### ISSUE THREAD

**Issue by hisplan** [mskcc/cmo#36]
When cmo_bwa_mem is called with `sam=False` (default), basically it pipes bwa mem with samtools:

```
bwa mem fasta fastq | samtools view -bh - > out.bam
```

The problem is if bwa fails, the exit code is 0, when we actually expects 1 (or throws an exception). Because of this, LSF reports that the job is actually successful.

This behavior can be tested with this simple example:

```
exit_code = subprocess.check_call("false | true", shell=True)
```

Again, this returns 0 when expecting 1.

One of the workarounds is using `set -o pipefail` to force bash to behave.

```
set -o pipefail; bwa mem fasta fastq | samtools view -bh - > out.bam
```

Another is spawning two subprocesses and chaining them later.

**Comment by lordzappo** [comment]
set -o pipefail will appear in this release

https://github.com/mskcc/cmo/releases/tag/1.4.4

see if that brings joy

**Comment by hisplan** [comment]
Working great. Thanks.
