### ISSUE TITLE
ValueError: Could not get next FW id! 

### ISSUE THREAD

**Issue by jsmedmar** [mskcc/cmo#5]
I'm trying to run cmoflow_facets:

`/opt/common/CentOS_6-dev/python/python-2.7.10/bin/cmoflow_facets`

However, It seems that I missed some configuration and I'm getting this error:

`ValueError: Could not get next FW id! If you have not yet initialized the database, please do so by performing a database reset (e.g., lpad reset)`

As suggested, I ran:

`/opt/common/CentOS_6-dev/python/python-2.7.10/bin/lpad reset`

But I kept getting the same error.

Would appreciate any help, first time running a cmo worflow!

**Comment by lordzappo** [comment]
what is your cbio username?

The first time you run a cmoflow command, there is some console
interactivity.  If you ran this bsubbed or headless, you miss the chance to
respond to the prompts.

I will reset/setup your database for you and you should be good to go.

The cmoflow_facets commands can be run on s01, and then the console will be
returned to you - it will launch a workflow daemon in your name on s01.

After I get your username, I'll reply again and let you know when you can
launch it.

Thanks!
CCH

**Comment by jsmedmar** [comment]
Hey CCH, thanks for your quick response! my user name is medinaj

**Comment by lordzappo** [comment]
Perfect, I've reset your database.

Here is your monitoring page:
https://haystack.mskcc.org/workflows/medinaj/

which is correctly empty right now.

Launch a workflow and refresh this page to see the progress of said
workflow.

Let me know if you have any problems,
CCH

**Comment by jsmedmar** [comment]
Its working now, thank you!

**Comment by lordzappo** [comment]
these jobs errored out because they can't find "rlaunch".

is /opt/common/CentOS_6-dev/python/python-2.7.10/bin/ in your PATH in
~/.profile or ~/.bashrc?

**Comment by jsmedmar** [comment]
I see, I was using the entire path to cmoflow_facets, I'm now going to export that path to my environment.

**Comment by lordzappo** [comment]
This is a failure mode we hadn't considered before.  I think in this case,
we need to start a new daemon to get the new environment variables in the
daemon's environment.

From a shell with the new environment variables (where "rlaunch" is in your
path, i.e. you can tab-complete rlaunch from any directory) can you type
"cmo_watcher -f"

**Comment by jsmedmar** [comment]
Got this output:

```
medinaj$ cmo_watcher -f

writing log to /ifs/res/pwg/logs/fireworks_workflows/medinaj/daemon.log
Using /opt/common/CentOS_6-dev/cmo/fireworks_config_files/medinaj.yaml launchpad config
Found process pid for Daemon: 43327
Killing...
Something went wrong in process kill..l bailing out
```

**Comment by jsmedmar** [comment]
I ran `export PATH=$PATH:/opt/common/CentOS_6-dev/python/python-2.7.10/bin/` to update my environment.

**Comment by lordzappo** [comment]
The export looks great.  I had a typo in the kill signal portion of the
code.  I've just patched it and reinstalled, and it worked on my daemon.

can you try issuing cmo_watcher -f one more time?

Thanks!
CCH

**Comment by jsmedmar** [comment]
This time:

```
medinaj$ cmo_watcher -f
writing log to /ifs/res/pwg/logs/fireworks_workflows/medinaj/daemon.log
Using /opt/common/CentOS_6-dev/cmo/fireworks_config_files/medinaj.yaml launchpad config
Found process pid for Daemon: 43327
Killing...
Removing database record!
{u'ok': 1, u'n': 1}
```

**Comment by lordzappo** [comment]
Great this looks better now: https://haystack.mskcc.org/workflows/medinaj/

Let me know if this isn't full green in an hour or two.

CCH

**Comment by lordzappo** [comment]
ps sorry for the first time pain.  future utilization should be much less
painful.

**Comment by ckandoth** [comment]
Thx for the feedback @jsmedmar. I've updated the readme to be more helpful.
