### ISSUE TITLE
Clone this repo at luna.

### ISSUE THREAD

**Issue by jsmedmar** [mskcc/cmo#7]
Hello, 

We would like to include some of your pipelines in our workflows, however my team is concerned with the fact that we can't control how the repo is updated. We would like to have some sort of a "sealed" copy that will work always the same way. Wondering if I clone the repo in luna, using my own python 2 installation, would the pipelines still work? I'm not sure if the mongodb settings will still work.

What are your thoughts?

Best!

**Comment by ckandoth** [comment]
Hi @jsmedmar. By "sealed" copy, do you mean a versioned release? As more users expect a stable version, that definitely makes sense. Let me know if you meant something else.

@lordzappo, can you confirm that I can tag a v0.1.0 release at https://github.com/mskcc/cmo/releases? Then I'll set it up at `/opt/common/CentOS_6` instead of `/opt/common/CentOS_6-dev`.

**Comment by lordzappo** [comment]
Tags are already implicitly set on installation by git hash. No version is
ever overwritten on luna, but we may need to change the front end scripts
to allow people to select versions. This use case is 80% xpected done we
just need to finish a few things.

With respect to mongo, nothing will change so you can clone or fork any of
our repos and install it in a path of your own or with --user.

I don't think installing it in non dev is a good idea it seems confusing
without benefit

**Comment by lordzappo** [comment]
If you are interested in the main pipeline workflow, be advised I am
working through some issues with the workflow software author w.r.t.
resuming jobs in very large (3000 job+) workflows.  It works, but it's
unusually slow.

This is a problem that will be resolved, but that workflow is not yet
production ready in the case of failure.

CCH

**Comment by ckandoth** [comment]
@jsmedmar All installed versions of this repo and its workflows, can be found on luna at `/opt/common/CentOS_6-dev/python/python-2.7.10/lib/python2.7/site-packages/cmo-*`. There should be an elegant way for users to choose between eggs. But in the meantime, you can do something like this to make sure you're using the `e766ccf` tagged release of this repo:

``` bash
export PATH=/opt/common/CentOS_6-dev/python/python-2.7.10/lib/python2.7/site-packages/cmo-e766ccf-py2.7.egg/EGG-INFO/scripts:$PATH
```

**Comment by ckandoth** [comment]
Closing issue since we're now using Toil-based workflows instead of Fireworks.
